server:
  port: 8081

spring:
  application:
    name: credit-card-backend

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27018/creditcarddb?authSource=admin

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO
    com.lbg.creditcard: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: sljfkdfsddkfjdfjsfldkfownvowndndsdwnds

  expiration: 86400000   # 1 day (milliseconds)

app:
  cors:
    allowed-origins: http://localhost:3000
